logging:
    level:
        root: INFO
        org.springframework.security: TRACE
        org.springframework.web: INFO
        org.springframework.security.oauth2: TRACE

server:
    port: 9000

spring:
    application:
        name: authorizationserver
    datasource:
        url: jdbc:postgresql://localhost:5432/learn-language
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
#    security:
#        oauth2:
#            authorization-server:
#                client:
#                    gateway:
#                        registration:
#                            client-id: "client"
#                            client-authentication-methods:
#                                - "client_secret_basic"
#                            authorization-grant-types:
#                                - "authorization_code"
#                                - "refresh_token"
#                                - "client_credentials"
#                            redirect-uris:
#                                - "http://localhost:8080/login/oauth2/code/gateway"
#                            post-logout-redirect-uris:
#                                - "http://localhost:8080/"
#                            scopes:
#                                - "openid"
#                                - "profile"
#                        require-authorization-consent: false
#                        require-proof-key: false
#                    google-idp:
#                        provider: google
#                        client-id: 740105852886-vnb5tor6u4rgns26cflpb4ei5ks0mknd.apps.googleusercontent.com
#                        client-secret: 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
#                        scope:
#                            - openid
#                            - profile
#                            - email
#                        client-name: Sign in with Google
#                provider:
#                    google:
#                        authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
#                        issuer-uri: https://accounts.google.com
#                        jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
#                        user-name-attribute: email

