server:
    port: 9000

spring:
    application:
        name: authorization-server
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:postgresql://localhost:5432/learn-language
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html

logging:
    level:
        root: INFO
        org.springframework.security: TRACE
        org.springframework.web: INFO
        org.springframework.security.oauth2: TRACE

---

server:
    port: 9000

spring:
    application:
        name: authorization-server
    config:
        activate:
            on-profile: production
    datasource:
        url: ${DATABASE_URL}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html