spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: dev
    import: "configserver:http://localhost:8088"
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: main-service-words
          uri: lb://main-service
          predicates:
            - Path=/api/v1/words/**
        - id: main-service-swagger
          uri: lb://main-service
          predicates:
            - Path=/main-service/v3/api-docs
        - id: word-service
          uri: lb://word-service
          predicates:
            - Path=/api/v1/word/**
        - id: word-service-translation
          uri: lb://word-service
          predicates:
            - Path=/api/v1/translation/**
        - id: word-service-swagger
          uri: lb://word-service
          predicates:
            - Path=/word-service/v3/api-docs
        - id: angular
          uri: http://localhost:8081/
          predicates:
            - Path=/**
        - id: angular
          uri: http://localhost:8081/words/
          predicates:
            - Path=/words
          filters:
            - SetPath=/words
  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: "client"
            client-secret: "secret"
            provider: "spring"
            authorization-grant-type: "authorization_code"
            scope: "openid, profile"
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            client-name: "gateway"
        provider:
          spring:
            issuer-uri: "http://localhost:9000"

---

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: production
    import: optional:configserver:${CONFIG_IP}
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: main-service-words
          uri: lb://main-service
          predicates:
            - Path=/api/v1/words/**
        - id: main-service-swagger
          uri: lb://main-service
          predicates:
            - Path=/main-service/v3/api-docs
        - id: word-service
          uri: lb://word-service
          predicates:
            - Path=/api/v1/word/**
        - id: word-service-translation
          uri: lb://word-service
          predicates:
            - Path=/api/v1/translation/**
        - id: word-service-swagger
          uri: lb://word-service
          predicates:
            - Path=/word-service/v3/api-docs
        - id: angular
          uri: ${FRONTEND}
          predicates:
            - Path=/**
  security:
    oauth2:
      client:
        registration:
          gateway:
            client-id: "client"
            client-secret: "secret"
            provider: "spring"
            authorization-grant-type: "authorization_code"
            scope: "openid, profile"
            redirect-uri: ${REDIRECT_URI}
            client-name: "gateway"
        provider:
          spring:
            issuer-uri: ${ISSUER_URI}