spring:
  application:
    name: word-service
  config:
    import: configserver:http://localhost:8088
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/words
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000

---

spring:
  application:
    name: word-service
  config:
    import: optional:configserver:http://host.docker.internal:8088
    activate:
      on-profile: production
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${ISSUER_URI}