server:
  servlet:
    context-path:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.config: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /word-service/v3/api-docs
        name: Word Service
      - url: /main-service/v3/api-docs
        name: Main Service