server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: https://discovery-service-qq0j.onrender.com/

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web: INFO
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.config: DEBUG

openapi:
  service:
    title: main-service doc
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /main-service/v3/api-docs
  swagger-ui:
    path: /main-service/swagger-ui.html