server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}

logging:
  level:
    root: INFO
    org.springframework.security: TRACE
    org.springframework.web: INFO
    org.springframework.security.oauth2: TRACE

openapi:
  service:
    title: word-service doc
    version: 1.0.0
    url: http://localhost:8080 #api gateway url
springdoc:
  api-docs:
    path: /word-service/v3/api-docs
  swagger-ui:
    path: /word-service/swagger-ui.html